# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: 
  password: 
  pool: 5

development:
  <<: *default
  database: blog-sample

production:
  <<: *default
  database: blog-sample
